version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reading-system
    ports:
      - "5431:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - reading-system

  reading-system:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: reading-system
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    networks:
      - reading-system

volumes:
  postgres_data:
    driver: local

networks:
  reading-system:
    name: reading-system
    driver: bridge
